# Base configs
baseurl: "https://f23-photography.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography f23-Photo_Group"
subtitle: "See the world through our eyes!"
author: "f23-Photo_Group"
header:
 title: "Photography"
 subtitle: "f23-Photo_Group"
footer:
 name: "Hey there, we are f23-Photo_Group"
 bio: "We are a small group of photographers who meet regularly to talk about the world, our lives, yes even photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'

